### ISSUE TITLE
XSUAA Configuration is missing  for Junit Controller.

### ISSUE THREAD

**Issue by junaid88** [SAP/cloud-security-services-integration-library#1185]
Hi,

I try to test the Controller endpoint in our CAP application where we used XSUAA .  

SecurityConfig.java
```
import com.sap.cloud.security.xsuaa.XsuaaServiceConfiguration;
import com.sap.cloud.security.xsuaa.token.TokenAuthenticationConverter;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.core.annotation.Order;
import org.springframework.core.convert.converter.Converter;
import org.springframework.security.authentication.AbstractAuthenticationToken;
import org.springframework.security.config.annotation.method.configuration.EnableGlobalMethodSecurity;
import org.springframework.security.config.annotation.web.builders.HttpSecurity;
import org.springframework.security.config.annotation.web.configuration.EnableWebSecurity;
import org.springframework.security.config.http.SessionCreationPolicy;
import org.springframework.security.oauth2.jwt.Jwt;
import org.springframework.security.web.SecurityFilterChain;

@Configuration
@EnableWebSecurity
@Order(1) // needs to have higher priority than CAP security config
public class SecurityConfiguration {

    @Autowired
    private XsuaaServiceConfiguration xsuaaServiceConfiguration;

    @Bean
    public SecurityFilterChain appFilterChain(HttpSecurity http) throws Exception {
        http
            .sessionManagement().sessionCreationPolicy(SessionCreationPolicy.STATELESS)
            .and()
                .requestMatchers().antMatchers("/odata/v4/ruleservices/**").and()
                .csrf().disable() // don't insist on csrf tokens in put, post etc.
                .authorizeRequests().anyRequest().permitAll()
            .and()
                .oauth2ResourceServer()
                .jwt()
                .jwtAuthenticationConverter(getJwtAuthenticationConverter());
        return http.build();
    }

    /**
     * Customizes how GrantedAuthority are derived from a Jwt
     */
    Converter<Jwt, AbstractAuthenticationToken> getJwtAuthenticationConverter() {
        final TokenAuthenticationConverter converter = new TokenAuthenticationConverter(xsuaaServiceConfiguration);
        converter.setLocalScopeAsAuthorities(true);
        return converter;
    }
}
```

But when i try to run the Junit test i got the following error 

`Error creating bean with name 'securityConfiguration': Unsatisfied dependency expressed through field 'xsuaaServiceConfiguration'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.sap.cloud.security.xsuaa.XsuaaServiceConfiguration' available: expected at least 1 bean which qualifies as autowire candidate. `

One way to resolve this issue is to add default-env.json file which contain XSUAA definition. But i would like to know the recommended way.

In the example provided by SAP cloud SDK https://github.com/SAP/cloud-security-services-integration-library/blob/a950b721a0596d6ece95c6669e5c172c88b4a5f7/samples/spring-security-xsuaa-usage junit tests are running without any external configurations. 

I try to do the same in my project but i keep getting same error.

Regards,
Junaid

**Comment by finkmanAtSap** [comment]
Hello Junaid,

the spring-security-xsuaa-usage sample uses the java-security-test module to start a WireMock server on localhost with stubbed responses for the XSUAA endpoints.
It is correct usage to specify the XSUAA configuration via Spring properties to target this server.

The sample does it via @TestPropertySource annotation in their JUnit test:
https://github.com/SAP/cloud-security-services-integration-library/blob/a950b721a0596d6ece95c6669e5c172c88b4a5f7/samples/spring-security-xsuaa-usage/src/test/java/sample/spring/xsuaa/TestControllerTest.java#L31

But it does not matter how you set the Spring properties. For example, you can set the Spring properties in an application.yml profile that you use only for testing or an application.properties file that you use only for testing. For more details please see these guides:
https://github.com/SAP/cloud-security-services-integration-library/tree/a950b721a0596d6ece95c6669e5c172c88b4a5f7/java-security-test#spring-boot
https://github.com/SAP/cloud-security-services-integration-library/tree/main/spring-security#overriding-identity-service-configurations

Setting a VCAP_JSON into the environment is not the recommended way though.

Best,
Manuel

From: Junaid Mohiuddin ***@***.***>
Date: Thursday, 27. April 2023 at 12:22
To: SAP/cloud-security-services-integration-library ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [SAP/cloud-security-services-integration-library] XSUAA Configuration is missing for Junit Controller. (Issue #1185)

Hi,

I try to test the Controller endpoint in our CAP application where we used XSUAA .

SecurityConfig.java

import com.sap.cloud.security.xsuaa.XsuaaServiceConfiguration;

import com.sap.cloud.security.xsuaa.token.TokenAuthenticationConverter;

import org.springframework.beans.factory.annotation.Autowired;

import org.springframework.context.annotation.Bean;

import org.springframework.context.annotation.Configuration;

import org.springframework.core.annotation.Order;

import org.springframework.core.convert.converter.Converter;

import org.springframework.security.authentication.AbstractAuthenticationToken;

import org.springframework.security.config.annotation.method.configuration.EnableGlobalMethodSecurity;

import org.springframework.security.config.annotation.web.builders.HttpSecurity;

import org.springframework.security.config.annotation.web.configuration.EnableWebSecurity;

import org.springframework.security.config.http.SessionCreationPolicy;

import org.springframework.security.oauth2.jwt.Jwt;

import org.springframework.security.web.SecurityFilterChain;



@Configuration

@EnableWebSecurity

@Order(1) // needs to have higher priority than CAP security config

public class SecurityConfiguration {



    @Autowired

    private XsuaaServiceConfiguration xsuaaServiceConfiguration;



    @Bean

    public SecurityFilterChain appFilterChain(HttpSecurity http) throws Exception {

        http

            .sessionManagement().sessionCreationPolicy(SessionCreationPolicy.STATELESS)

            .and()

                .requestMatchers().antMatchers("/odata/v4/ruleservices/**").and()

                .csrf().disable() // don't insist on csrf tokens in put, post etc.

                .authorizeRequests().anyRequest().permitAll()

            .and()

                .oauth2ResourceServer()

                .jwt()

                .jwtAuthenticationConverter(getJwtAuthenticationConverter());

        return http.build();

    }



    /**

     * Customizes how GrantedAuthority are derived from a Jwt

     */

    Converter<Jwt, AbstractAuthenticationToken> getJwtAuthenticationConverter() {

        final TokenAuthenticationConverter converter = new TokenAuthenticationConverter(xsuaaServiceConfiguration);

        converter.setLocalScopeAsAuthorities(true);

        return converter;

    }

}

But when i try to run the Junit test i got the following error

Error creating bean with name 'securityConfiguration': Unsatisfied dependency expressed through field 'xsuaaServiceConfiguration'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.sap.cloud.security.xsuaa.XsuaaServiceConfiguration' available: expected at least 1 bean which qualifies as autowire candidate.

One way to resolve this issue is to add default-env.json file which contain XSUAA definition. But i would like to know the recommended way.

In the example provided by SAP cloud SDK https://github.com/SAP/cloud-security-services-integration-library/blob/a950b721a0596d6ece95c6669e5c172c88b4a5f7/samples/spring-security-xsuaa-usage junit tests are running without any external configurations.

I try to do the same in my project but i keep getting same error.

Regards,
Junaid

**Comment by junaid88** [comment]
Hi Manuel,

Well i still face the same error after adding the following lines to the code 
`@TestPropertySource(properties = {"xsuaa.uaadomain=localhost", "xsuaa.xsappname=xsapp!t0815", "xsuaa.clientid=sb-clientId!t0815" })`

I also try to add the following properties to the application.yaml. 
```
sap:
  security:
    services:
      xsuaa:
        xsappname: xsapp!t0815
        uaadomain: localhost
        clientid: sb-clientId!t0815
        clientsecret: pwd
        url: http://localhost
      identity:
        clientid: sb-clientId!t0815
        domains: localhost
```

As i said earlier i am only able to resolve that issue when i provide the VCAP_JSON into the default-env.json.

Regards,
Junaid

**Comment by finkmanAtSap** [comment]
Hi Junaid,

Can you please provide all the information mentioned in the spring-xsuaa documentation here?
https://github.com/SAP/cloud-security-services-integration-library/tree/main/spring-xsuaa#troubleshooting

Are you using spring-xsuaa or spring-security? With starter or without? Which version of our lib etc.?

**Comment by junaid88** [comment]
Hi Manuel,

Please find all the relevant information in the attachment.

- [mvn_dependency_tree.txt](https://github.com/SAP/cloud-security-services-integration-library/files/11384187/mvn_dependency_tree.txt)
- [debugLogs.txt](https://github.com/SAP/cloud-security-services-integration-library/files/11384190/debugLogs.txt)
- We are using SAP Machine JDK17 as java buildpack.

Well we are using xsuaa-spring-boot-starter version 2.13.5 (spring-xsuaa) not directly [CAP ](https://cap.cloud.sap/docs/java/security?q=xsuaa+#xsuaa )framework provided it.

**Comment by finkmanAtSap** [comment]
Hi Junaid,

Thank you for the information.
As you are using xsuaa-spring-boot-starter version 2.13.5 , the missing XsuaaServiceConfiguration bean should be created in this place here:
https://github.com/SAP/cloud-security-services-integration-library/blob/2.13.5/spring-xsuaa/src/main/java/com/sap/cloud/security/xsuaa/autoconfiguration/XsuaaAutoConfiguration.java#L48
So we need to find out why this code is not running.

As you can see, the creation of the Bean is conditional based on all of these:
@ConditionalOnProperty(prefix = "spring.xsuaa", name = "auto", havingValue = "true", matchIfMissing = true)
@ConditionalOnProperty(prefix = "spring.xsuaa", name = "multiple-bindings", havingValue = "false", matchIfMissing = true)
@ConditionalOnProperty(prefix = "spring.xsuaa", name = "disable-default-property-source", havingValue = "false", matchIfMissing = true)

The easiest way to find out which condition is failing, is to let Spring Boot create a report for us that should tell us the reason: https://www.baeldung.com/spring-boot-auto-configuration-report

It could also be the case that XsuaaAutoConfiguration class does not get picked up by the Spring context when you run your JUnit test, even though it has @Configuration annotation. In that case, you need to find out why. Could be related to 
`@SpringBootTest(classes = ...)` or maybe CAP is doing some magic but unfortunately I don't have enough experience with CAP to help in that regard.
