### ISSUE TITLE
alternative for com.sap.cloud.security.adapter.xs.XSUserInfoAdapte  in 3.x serial. 

### ISSUE THREAD

**Issue by flyingbug** [SAP/cloud-security-services-integration-library#1280]
hello colleagues,
We are trying to migration java-security client from 2.x to 3.x. During the migration , it seems com.sap.cloud.security.adapter.xs.XSUserInfoAdapter was dropped in 3.x while it exists in 2.x.  As our code still has dependency for this logic, is there any alternative for it?   Could you please share us an example for how to implement the same logic with 3.x? Great thanks. 

 Our case looks like this:
 final AccessToken token = SecurityContext.getAccessToken();
 final XSUserInfo userInfo = new XSUserInfoAdapter(token);
 String  saml = userInfo.getHdbToken();

Best regards,
Andy

**Comment by finkmanAtSap** [comment]
Hi Andy,

If you need the legacy API in 3.x, you need to provide the adapter class in your codebase. Feel free to copy our XSUserInfoAdapter to get started but we decided to remove it as XSUserInfo has been deprecated in favor of a new Token interface since version 2.4.0 already.
The new Token interface has been adjusted for different structural changes of the token payload, so it is up-to-date with changes by the authentication services. Unfortunately we cannot maintain this for the legacy adapters as well.

Best,
Manuel

**Comment by flyingbug** [comment]
hi Manuel, 

Thank your for your help. It seems that we have to fill the gap by ourselves.  We can start from copying XSUserInfoAdapter from 2.x.  

Best regards,
Andy

**Comment by finkmanAtSap** [comment]
Yes, exactly. Thank you for your understanding.

Best,
Manuel
