### ISSUE TITLE
Plans on upgrading to Spring Boot 3 when it is officially released?

### ISSUE THREAD

**Issue by edmundham** [SAP/cloud-security-services-integration-library#809]
Hi team,

I see that this library has a frequent Spring Boot version updates and try to keep the latest, so thought of asking this question.

Spring Boot 3.x is planned to be released in 2022 Q4 (Oct) https://spring.io/blog/2022/01/20/spring-boot-3-0-0-m1-is-now-available 
However, minimum Java version for Spring Boot 3 will be Java 17.

**My main question is: Do you have plans on upgrading to Spring Boot 3 when it is officially released?**

I'm not asking to upgrade, just wondering as I can see frequent spring boot upgrade in this library and if you are planning on it, I have to get my project ready for it too.

**Comment by liga-oz** [comment]
Hi @edmundham,

thanks for your question. We haven't looked into this topic yet in details, but it would take quite some efforts for us to switch over to Spring Boot 3, mainly due to the fact that Java EE APIs would need to be migrated to Jakarta EE and with that we would also want to bump the [Tomcat](https://github.com/SAP/cloud-security-xsuaa-integration/issues/499) version for non Spring modules. In addition, we need to take into consideration that not all Spring features will be fully supported at the beginning of Spring Boot 3. Long story short, we will eventually switch over to Spring Boot 3, but there is not yet clear timeline when.

Kind Regards,
Liga

**Comment by rjayasinghe** [comment]
As the release of Spring Boot 3 is around the corner I'd like to know if you have come to a conclusion about a timeline wrt. Spring Boot 3 or Spring Security 6 support for XSUAA.

We (the CAP Java development team) have already started the next major version of CAP Java which will integrate with Spring Boot 3 (and only that version) and Spring Security 6. In order to proceed with that efforts we will need a version of the spring-xsuaa that supports Spring Boot 3.

So, a timeline and/or pointers to release candidates / milestone builds that already support Spring Boot 3 would really be great. Thanks!

**Comment by liga-oz** [comment]
@edmundham , @rjayasinghe The migration to Spring 6 , Spring boot 3 is planned for 2023 Q2

**Comment by liga-oz** [comment]
Closing this issue as the major version 3.0.0 which supports Spring Boot 3 and Spring Framework 6 has been released.
